
import { Language } from "./types";

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "Wise Weather",
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.alerts": "Alerts",
    "nav.feedback": "Feedback",
    "weather.official_forecast": "Official Forecast",
    "weather.hourly": "Hourly Forecast",
    "weather.wind": "Wind",
    "weather.humidity": "Humidity",
    "weather.sunrise": "Sunrise",
    "weather.sunset": "Sunset",
    "weather.visibility": "Visibility",
    "weather.pollution": "Pollution",
    "weather.feelsLike": "Feels Like",
    "community.title": "Weather Community",
    "community.official": "OFFICIAL",
    "community.reports": "COMMUNITY",
    "community.confidence": "Confidence",
    "map.toggle.official": "Official Forecasts",
    "map.toggle.community": "Community Reports",
    "map.search.placeholder": "e.g., Paris, France",
    "map.search.button": "Search",
    "modal.title": "What's the weather?",
    "modal.desc": "Help the community by reporting real-time conditions.",
    "modal.select_hint": "SELECT UP TO 3 ELEMENTS TO SHARE THE WEATHER NOW",
    "modal.submit": "Share Report",
    "modal.wait": "Skip in",
    "alert.title": "RAIN ALERT",
    "alert.desc": "Get notified when rain is coming.",
    "alert.city": "City & Country",
    "alert.rain": "Rain",
    "alert.create": "Create Rain Alert",
    "alert.existing": "Active Alert",
    "alert.active": "Active",
    "alert.monitoring": "Monitoring for Rain",
    "alert.warning.title": "SEVERE WEATHER WARNING",
    "alert.warning.desc": "Storm conditions detected in your area. Please stay safe.",
    "feedback.bug": "Report a bug",
    "feedback.feature": "Request a feature",
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Please confirm you accept notifications to be part of the community.",
    "modal.notifications.accept": "Accept Notifications",
    "modal.notifications.cancel": "No thanks",
    "gamification.feedback": "Observation integrated. Local precision: +{{val}}% for the next hour.",
    "gamification.first": "🌟 BRAVO, you were the fastest to provide weather info for the community 👏",
    "gamification.fifth": "💫 BRAVO, your contribution validates local weather to 100% 👏",
    "modal.continue": "Continue",
    "gamification.cycle.0": "Great responsiveness! Thanks to you, we finally know what's happening.",
    "gamification.cycle.1": "Confirmation received. It's noted for everyone.",
    "gamification.cycle.2": "Thanks! The info has been sent up.",
    "gamification.cycle.3": "Eagle eye strikes again. Thanks!",
    "gamification.cycle.4": "It's in the bag. Local weather adjusted.",
    "gamification.cycle.5": "You rock! Thanks for the quick check.",
    "gamification.cycle.6": "Ok, recorded. Spreading the word.",
    "gamification.cycle.7": "Thanks for clearing up the situation!",
    "gamification.cycle.8": "Top! Nothing beats a human on site.",
    "gamification.cycle.9": "Update done. Your neighbors say thanks.",
    "gamification.cycle.10": "Information verified. You rule!",
    "gamification.cycle.11": "Weather point validated. Thanks for your vigilance."
  },
  fr: {
    "app.name": "Wise Weather",
    "nav.home": "Accueil",
    "nav.map": "Carte",
    "nav.alerts": "Alertes",
    "nav.feedback": "Avis",
    "weather.official_forecast": "Prévisions Officielles",
    "weather.hourly": "Prévisions Horaires",
    "weather.wind": "Vent",
    "weather.humidity": "Humidité",
    "weather.sunrise": "Lever du soleil",
    "weather.sunset": "Coucher du soleil",
    "weather.visibility": "Visibilité",
    "weather.pollution": "Pollution",
    "weather.feelsLike": "Ressenti",
    "community.title": "Communauté Météo",
    "community.official": "OFFICIEL",
    "community.reports": "COMMUNAUTÉ",
    "community.confidence": "Confiance",
    "map.toggle.official": "Prévisions Officielles",
    "map.toggle.community": "Rapports Communauté",
    "map.search.placeholder": "ex: Paris, France",
    "map.search.button": "Rechercher",
    "modal.title": "Quel temps fait-il ?",
    "modal.desc": "Aidez la communauté en signalant les conditions en temps réel.",
    "modal.select_hint": "SÉLECTIONNEZ JUSQU'À 3 ÉLÉMENTS POUR PARTAGER LA MÉTÉO MAINTENANT",
    "modal.submit": "Partager le rapport",
    "modal.wait": "Passer dans",
    "alert.title": "ALERTE PLUIE",
    "alert.desc": "Soyez notifié quand la pluie arrive.",
    "alert.city": "Ville & Pays",
    "alert.rain": "Pluie",
    "alert.create": "Créer Alerte Pluie",
    "alert.existing": "Alerte Active",
    "alert.active": "Actif",
    "alert.monitoring": "Surveillance Pluie",
    "alert.warning.title": "AVERTISSEMENT MÉTÉO SÉVÈRE",
    "alert.warning.desc": "Conditions orageuses détectées dans votre zone. Soyez prudent.",
    "feedback.bug": "Signaler un bug",
    "feedback.feature": "Suggérer une fonctionnalité",
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Veuillez confirmer accepter les notifications pour faire partie de la communauté.",
    "modal.notifications.accept": "Accepter les notifications",
    "modal.notifications.cancel": "Non merci",
    "gamification.feedback": "Observation intégrée. Précision locale : +{{val}}% pour la prochaine heure.",
    "gamification.first": "🌟 BRAVO, tu as été le plus rapide à donner une information météo pour la communauté 👏",
    "gamification.fifth": "💫 BRAVO, ta contribution valide à 100% la météo locale 👏",
    "modal.continue": "Continuer",
    "gamification.cycle.0": "Super réactivité ! Grâce à toi, on sait enfin ce qu'il se passe.",
    "gamification.cycle.1": "Confirmation reçue. C'est noté pour tout le monde.",
    "gamification.cycle.2": "Merci ! L'info est remontée.",
    "gamification.cycle.3": "Ton oeil de lynx a encore frappé. Merci !",
    "gamification.cycle.4": "C'est dans la boîte. La météo locale est ajustée.",
    "gamification.cycle.5": "Tu gères ! Merci pour ce check rapide.",
    "gamification.cycle.6": "Ok, c'est enregistré. On fait passer le mot.",
    "gamification.cycle.7": "Merci d'avoir éclairci la situation !",
    "gamification.cycle.8": "Top ! Rien ne vaut un humain sur place.",
    "gamification.cycle.9": "Mise à jour effectuée. Tes voisins te disent merci.",
    "gamification.cycle.10": "Information vérifiée. Tu assures !",
    "gamification.cycle.11": "Point météo validé. Merci pour ta vigilance."
  }
};
