
import { Language } from "./types";

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "Wise Weather",
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.alerts": "Alerts",
    "nav.feedback": "Feedback",
    "weather.official_forecast": "Official Forecast",
    "weather.hourly": "Hourly Forecast",
    "weather.wind": "Wind",
    "weather.humidity": "Humidity",
    "weather.sunrise": "Sunrise",
    "weather.sunset": "Sunset",
    "weather.feelsLike": "Feels Like",
    "community.title": "Weather Community",
    "community.official": "OFFICIAL",
    "community.reports": "COMMUNITY",
    "community.confidence": "Confidence",
    "map.toggle.official": "Official Forecasts",
    "map.toggle.community": "Community Reports",
    "map.search.placeholder": "e.g., Paris, France",
    "map.search.button": "Search",
    "modal.title": "What's the weather?",
    "modal.desc": "Help the community by reporting real-time conditions.",
    "modal.select_hint": "SELECT UP TO 3 ELEMENTS TO SHARE THE WEATHER NOW",
    "modal.submit": "Share Report",
    "modal.wait": "Skip in",
    "alert.title": "RAIN ALERT",
    "alert.desc": "Get notified when rain is coming.",
    "alert.city": "City & Country",
    "alert.rain": "Rain",
    "alert.create": "Create Rain Alert",
    "alert.existing": "Active Alert",
    "alert.active": "Active",
    "alert.monitoring": "Monitoring for Rain",
    "alert.warning.title": "SEVERE WEATHER WARNING",
    "alert.warning.desc": "Storm conditions detected in your area. Please stay safe.",
    "feedback.bug": "Report a bug",
    "feedback.feature": "Request a feature",
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Please confirm you accept notifications to be part of the community.",
    "modal.notifications.accept": "Accept Notifications",
    "modal.notifications.cancel": "No thanks"
  },
  fr: {
    "app.name": "Wise Weather",
    "nav.home": "Accueil",
    "nav.map": "Carte",
    "nav.alerts": "Alertes",
    "nav.feedback": "Avis",
    "weather.official_forecast": "Prévisions Officielles",
    "weather.hourly": "Prévisions Horaires",
    "weather.wind": "Vent",
    "weather.humidity": "Humidité",
    "weather.sunrise": "Lever",
    "weather.sunset": "Coucher",
    "weather.feelsLike": "Ressenti",
    "community.title": "Météo Communautaire",
    "community.official": "OFFICIEL",
    "community.reports": "COMMUNAUTÉ",
    "community.confidence": "Confiance",
    "map.toggle.official": "Prévisions Officielles",
    "map.toggle.community": "Rapports Communauté",
    "map.search.placeholder": "ex: Paris, France",
    "map.search.button": "Rechercher",
    "modal.title": "Quel temps fait-il ?",
    "modal.desc": "Aidez la communauté en signalant les conditions réelles.",
    "modal.select_hint": "SÉLECTIONNEZ JUSQU'À 3 ÉLÉMENTS POUR PARTAGER LA MÉTÉO",
    "modal.submit": "Partager",
    "modal.wait": "Passer dans",
    "alert.title": "ALERTE PLUIE",
    "alert.desc": "Soyez notifié de l'arrivée de la pluie.",
    "alert.city": "Ville & Pays",
    "alert.rain": "Pluie",
    "alert.create": "Créer l'alerte",
    "alert.existing": "Alerte Active",
    "alert.active": "Active",
    "alert.monitoring": "Surveillance Pluie",
    "alert.warning.title": "ALERTE MÉTÉO SÉVÈRE",
    "alert.warning.desc": "Conditions orageuses détectées. Soyez prudent.",
    "feedback.bug": "Signaler un bug",
    "feedback.feature": "Demander une fonction",
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Veuillez confirmer accepter les notifications pour faire partie de la communauté.",
    "modal.notifications.accept": "Accepter les notifications",
    "modal.notifications.cancel": "Non merci"
  }
};
