
import { Language } from "./types";

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "Wise Weather",
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.alerts": "Alerts",
    "nav.feedback": "Feedback",
    "weather.official_forecast": "Official Forecast",
    "weather.hourly": "Hourly Forecast",
    "weather.wind": "Wind",
    "weather.humidity": "Humidity",
    "weather.sunrise": "Sunrise",
    "weather.sunset": "Sunset",
    "weather.visibility": "Visibility",
    "weather.pollution": "Pollution",
    "weather.feelsLike": "Feels Like",
    "community.title": "Weather Community",
    "community.official": "OFFICIAL",
    "community.reports": "COMMUNITY",
    "community.confidence": "Confidence",
    "map.toggle.official": "Official Forecasts",
    "map.toggle.community": "Community Reports",
    "map.search.placeholder": "e.g., Paris, France",
    "map.search.button": "Search",
    "modal.title": "What's the weather?",
    "modal.desc": "Help the community by reporting real-time conditions.",
    "modal.select_hint": "SELECT UP TO 3 ELEMENTS TO SHARE THE WEATHER NOW",
    "modal.submit": "Share Report",
    "modal.wait": "Skip in",
    "alert.title": "RAIN ALERT",
    "alert.desc": "Get notified when rain is coming.",
    "alert.city": "City & Country",
    "alert.rain": "Rain",
    "alert.create": "Create Rain Alert",
    "alert.existing": "Active Alert",
    "alert.active": "Active",
    "alert.monitoring": "Monitoring for Rain",
    "alert.warning.title": "SEVERE WEATHER WARNING",
    "alert.warning.desc": "Storm conditions detected in your area. Please stay safe.",
    "feedback.bug": "Report a bug",
    "feedback.feature": "Request a feature",
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Please confirm you accept notifications to be part of the community.",
    "modal.notifications.accept": "Accept Notifications",
    "modal.notifications.cancel": "No thanks",
    "gamification.feedback": "Observation integrated. Local precision: +{{val}}% for the next hour."
  },
  fr: {
    "app.name": "Wise Weather",
    "nav.home": "Accueil",
    // ...
    "modal.notifications.title": "Notifications",
    "modal.notifications.desc": "Veuillez confirmer accepter les notifications pour faire partie de la communauté.",
    "modal.notifications.accept": "Accepter les notifications",
    "modal.notifications.cancel": "Non merci",
    "gamification.feedback": "Observation intégrée. Précision locale : +{{val}}% pour la prochaine heure."
  }
};
